name: minishell tester >> signals

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  testing_146_items:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Starting Github Actions
        uses: actions/checkout@v4.1.4

      - name: Building Program with MiniShell Makefile
        run: make

      - name: Submodule Init
        run: git submodule init && git submodule update

      - name: Running Tester for 146 items
        run: cd minishell_tester && ./tester manual_tests/signals


# :: source minishell_tester repository ::
# https://github.com/LucasKuhn/minishell_tester